export const GET_CITY_WEATHER_REQUEST = 'GET_CITY_WEATHER_REQUEST';
export const GET_CITY_WEATHER_SUCCESS = 'GET_CITY_WEATHER_SUCCESS';
export const CLEAN_CITY_WEATHER = 'CLEAN_CITY_WEATHER';
export const ADD_TO_DASH_BOARD = 'ADD_TO_DASH_BOARD';
export const ADD_TO_SELECT = 'ADD_TO_SELECT';
export const SET_RANGE_VALUE = 'SET_RANGE_VALUE';
export const DELETE_FROM_DASH_BOARD = 'DELETE_FROM_DASH_BOARD';